# Generated by Django 6.0.6 on 2026-07-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='tile')),
                ('author', models.CharField(max_length=150, verbose_name='author')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='published_date')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
            ],
        ),
    ]
